title: Peter Huang
email: peterhxk@gmail.com
name: "Peter Huang"
description: >-
  Home Page
baseurl: ""
url: "https://peterhxk.github.io"
github_username: peterhxk

# Theme and plugins
theme: null
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom layout
defaults:
  - scope:
      path: "" # Apply to all files in the project
    values:
      layout: "default" # Use the "default" layout
